Repository 1stLunchVote/1stLunchVote_Flutter_Release, pull requests merged in 2023-01, with the labels that each got.

#1 [Refactor] 프로필 화면 변경 및 iOS 상태바 변경
  lib/styles.dart
  lib/view/screen/home_screen.dart
  lib/view/screen/login_screen.dart
  lib/view/screen/profile_screen.dart
  pubspec.yaml
Labels: enhancement

#2 Appbar design & callback
  lib/view/screen/group/group_screen.dart
  lib/view/widget/appbar_widget.dart
Labels: enhancement

#5 [Impl] 홈화면 닉네임 자동 반영 및 프로필 화면 수정
  lib/controller/nickname_controller.dart
  lib/main.dart
  lib/view/screen/home_screen.dart
  lib/view/screen/profile_screen.dart
  pubspec.yaml
Labels: enhancement

#10 [Chore] baseUrl 숨기기 전체 설정
  lib/controller/first_vote_controller.dart
  lib/controller/group_controller.dart
  lib/controller/home_controller.dart
  lib/controller/login_controller.dart
  lib/controller/menu_controller.dart
  lib/controller/profile_controller.dart
  lib/controller/result_controller.dart
  lib/controller/second_vote_controller.dart
  lib/controller/template_controller.dart
  lib/controller/vote_state_controller.dart
  lib/repository/lunch_vote_service.dart
  pubspec.yaml
Labels: 설정

#11 LunchDialog widget화
  android/app/google-services.json
  ios/firebase_app_id_file.json
  lib/firebase_options.dart
  lib/main.dart
  lib/model/menu/menu_info.g.dart
  lib/view/screen/friend/friendlist_screen.dart
  lib/view/screen/home_screen.dart
  lib/view/widget/friend_tile.dart
  lib/view/widget/lunch_dialog.dart
  pubspec.lock
Labels: 리팩토링

#12 [Refactor] 2차 투표 및 로그인 화면 변경
  lib/controller/login_controller.dart
  lib/controller/nickname_controller.dart
  lib/controller/second_vote_controller.dart
  lib/model/vote/vote_item_notifier.dart
  lib/view/screen/home_screen.dart
  lib/view/screen/login_screen.dart
  lib/view/screen/vote/first_vote_screen.dart
  lib/view/screen/vote/second_vote_screen.dart
  lib/view/widget/lunch_button.dart
  lib/view/widget/second_vote_tile.dart
  pubspec.yaml
Labels: 설정, 화면, 리팩토링

#15 [Refactor] 2차 투표 화면 수정 및 스타일 수정
  lib/controller/notification_controller.dart
  lib/main.dart
  lib/styles.dart
  lib/view/screen/home_screen.dart
  lib/view/screen/login_screen.dart
  lib/view/screen/vote/second_vote_screen.dart
  lib/view/widget/utils/shared_pref_manager.dart
Labels: 버그, 설정, 화면

#17 [FIX] 푸시 알림 수정 및 2차투표 타이머 추가
  lib/controller/notification_controller.dart
  lib/controller/second_vote_controller.dart
  lib/main.dart
  lib/view/screen/vote/second_vote_screen.dart
Labels: 버그

#18 [FEAT] 1차 투표 타이머
  assets/images/friend_profile_default.png
  lib/controller/first_vote_controller.dart
  lib/controller/friends_controller.dart
  lib/controller/second_vote_controller.dart
  lib/main.dart
  lib/view/screen/friend/friendlist_screen.dart
  lib/view/screen/home_screen.dart
  lib/view/screen/vote/first_vote_screen.dart
  lib/view/screen/vote/result_screen.dart
  lib/view/screen/vote/second_vote_screen.dart
  lib/view/widget/friend_tile.dart
Labels: 버그, 화면, 기능

#19 [Refactor] 패키지 분리 및 아키텍쳐 설정
  assets/images/bg_result_rate.svg
  lib/binding/home_binding.dart
  lib/binding/login_binding.dart
  lib/binding/profile_binding.dart
  lib/controller/first_vote_controller.dart
  lib/controller/group_controller.dart
  lib/controller/home_controller.dart
  lib/controller/login_controller.dart
  lib/controller/menu_controller.dart
  lib/controller/notification_controller.dart
  lib/controller/profile_controller.dart
  lib/controller/result_controller.dart
  lib/controller/second_vote_controller.dart
  lib/controller/template_controller.dart
  lib/controller/vote_state_controller.dart
  lib/main.dart
  lib/provider/lunch_vote_dio_provider.dart
  lib/provider/lunch_vote_service.dart
  lib/provider/lunch_vote_service_provider.dart
  lib/repository/home_repository.dart
  lib/repository/profile_repository.dart
  lib/routes/app_pages.dart
  lib/routes/app_routes.dart
  lib/utils/shared_pref_manager.dart
  lib/view/screen/home_screen.dart
  lib/view/screen/login_screen.dart
  lib/view/screen/profile_screen.dart
  lib/view/screen/vote/result_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: 설정, 리팩토링
